name: .Xpenguin
description: A weekly Linux gaming podcast
url: http://xpenguin.club
mp3url: http://206.189.5.169/podcasts/
baseurl: ""
imagedir: "/images/"
twitter_username: HexDSL
welcome: "A weekly Linux gaming podcast hosted by [HexDSL](https://www.youtube.com/channel/UCRE3NFNtdjR96-H4QG4U1Fg) and [HamishTPB](https://www.youtube.com/channel/UCp1mWfjYbMcmNowBmvTUCag).
\n\nYou can subscribe to the podcast [here](/rss.xml) and find HexDSL on Youtube [here](https://www.youtube.com/channel/UCRE3NFNtdjR96-H4QG4U1Fg).
\n\nRecording of the podcast is streamed live on [Twitch](https://www.twitch.tv/hexdsl) every Saturday at 18:00 UK time."
defaults:
    -   
        scope:
            path: ""
            type: "posts"
        values:
            comments: false
            podcast: true
            layout: post
            author: hex
    -   
        scope:
            path: ""
            type: "drafts"
        values:
            comments: false
            layout: post
            author: hex
plugins: [jekyll-paginate]
paginate: 5
paginate_path: "/:num"
links:
    Atom Feed:
        url: /rss.xml 
        image: atom_icon.png
    Youtube:
        url: https://www.youtube.com/channel/UCRE3NFNtdjR96-H4QG4U1Fg
        image: youtube_icon.png
    Mastodon:
        url: https://linuxrocks.online/@HexDSL
        image: mastodon_icon.png
    Twitter:
        url: https://twitter.com/HexDSL
        image: twitter_icon.png
    Twitch:
        url: https://www.twitch.tv/hexdsl/
        image: twitch_icon.png
    Discord:
        url: https://discord.gg/usPdBTt
        image: discord_icon.png
authors:
    hex:
        name: HexDSL
        link: https://www.youtube.com/channel/UCRE3NFNtdjR96-H4QG4U1Fg
        email: hexdsl@protonmail.com
# !! You don't need to change any of the configuration flags below !!
#

#markdown: redcarpet
#highlighter: pygments
permalink: /:title/
